#############################################################################################
# INFORMAÇÕES
# 
# Arquivo para implantação de uma Lading Page em um cluster Docker Swarm com Traefik Proxy:
# > Docker version 24.0.2, build cb74dfc
# > Traefik version 2.2
#############################################################################################

version: '3.7'

services:
  webpage:
    image: webpage:latest
    networks:
      - traefik-public
    configs:
      - source: webpage_conf
        target: /etc/nginx/conf.d/default.conf
    # command: [nginx-debug, '-g', 'daemon off;']
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first   
      labels:  
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.webpage-http.rule=Host(`${SITE_DOMAIN?Variable not set}`)
        - traefik.http.routers.webpage-http.entrypoints=http
        - traefik.http.routers.webpage-http.middlewares=https-redirect
        - traefik.http.routers.webpage-https.rule=Host(`${SITE_DOMAIN?Variable not set}`)
        - traefik.http.routers.webpage-https.entrypoints=https
        - traefik.http.routers.webpage-https.tls=true
        - traefik.http.routers.webpage-https.tls.certresolver=le
        - traefik.http.services.webpage.loadbalancer.server.port=80

networks:
  traefik-public:
    external: true

configs:
  webpage_conf:
    file: ./conf/default.conf
    name: webpage_conf